<?php
if ($this->session->has("username")) {
   $username = $this->session->get("username");
}
else{
	$user = "Guest";
}
?>

<div class="col-sm-10 col-md-10">
	<h3 class="title">Hello, <?php echo $username; ?>!</h3>
	<p>From your My Account Dashboard you have the ability to view a snapshot of your recent account activity and update your account information. Select a link below to view or edit information.</p>
	<h3 class="sub-header">Recent Orders</h3>
	<div class="table-responsive">
		<table class="table table-striped">
		  <thead>
			<tr>
			  <th>Order #</th>
			  <th>Date</th>
			  <th>Ship To</th>
			  <th>Order Total</th>
			  <th>Status</th>
			</tr>
		  </thead>
		  <tbody>
			<tr>
			  <td>1,001</td>
			  <td>Lorem</td>
			  <td>ipsum</td>
			  <td>dolor</td>
			  <td>sit</td>
			</tr>
			<tr>
			  <td>1,001</td>
			  <td>Lorem</td>
			  <td>ipsum</td>
			  <td>dolor</td>
			  <td>sit</td>
			</tr>
		  </tbody>
		</table>
	</div>
	<?php $this->partial("user/account/info"); ?>
	<?php $this->partial("user/account/address"); ?>
</div>

