<?php $address = Address::getShippingAddress(); ?>
<div class="col-sm-6 col-md-6 user-address">
	<h6 class="col-sm-6 col-md-6 "><strong>Default Shipping Address</strong></h6>
	<h6 class="col-sm-6 col-md-6 "><a class="formlink" href="/user/address/edit/<?php echo $address->address_id; ?>">Edit Address</a></h6>
	<?php
		if(count($address) > 0){
			?>
				<div class="address col-sm-9 col-md-9 panel panel-default col-md-offset-0">
					<p><?php echo $this->helpers->getUserAddress($address->street); ?></p>
					<p><?php echo $address->city; ?>, <?php echo $address->state; ?></p>
					<p><?php echo $address->zip; ?> - <?php echo $address->country; ?></p>
					<p><?php echo $address->company; ?>,<?php echo $address->telephone; ?></p>
				</div>
			<?php
		}
		else{
			echo "Sorry! No Address Found.";
		}
	?>
</div>