<div class="col-sm-12 col-md-12 remove-padding">
	<h3 class="sub-header">Account Information</h3>
	<span class="edit"><a href="/user/edit">Edit</a></span>
	<?php 
		if ($this->session->has("username")) :
			$username = $this->session->get("username");
			$user = new Users;
			$user = $user::findFirstByUsername($username);
		?>
			<div class="col-sm-10 col-md-10">
				<p class="text-capitalize"><?php echo $user->firstname. ' '. $user->lastname; ?></p>
				<p><?php echo $user->email; ?></p>
			</div>
		<?php
		endif;
	?>
</div>