<div class="col-sm-3 col-md-2 vertical-menu">
	<ul class="nav nav-sidebar">
		<li class="active"><a href="/user/account">Account Dashboard <span class="sr-only">(current)</span></a></li>
		<li><a href="/user/account/edit">Account Information</a></li>
		<li><a href="/user/address/">Address Book</a></li>
		<li><a href="#">My Orders</a></li>
		<li><a href="#">My Wishlist</a></li>
		<li><a href="#">My Posts</a></li>
		<li><a href="#">My Fan's Following</a></li>
		<li><a href="#">My Images</a></li>
		<li><a href="#">Send Invite</a></li>
	</ul>
</div>