<div class="login" id="login">
	<div class="col-sm-9 col-md-9 panel-body">
		<div class="panel panel-default">
			<div class="panel-body col-md-offset-5"><h2>Change Password</h2></div>
			<div class="panel-footer">
				<form method="post" action="/user/changepassword" class="form-horizontal col-md-offset-2">
					<input type="hidden" name="<?php echo $this->security->getTokenKey() ?>"
						value="<?php echo $this->security->getToken() ?>"/>
						<input type="hidden" name="email"
						value="<?php echo $this->request->get('email') ?>"/>
					<fieldset>
						<div class="form-group">
							<div class="col-lg-10 col-xs-10 col-sm-10 col-md-10 ">
								<div class="input-group">
									<span class="input-group-addon">
										<span class="glyphicon glyphicon-lock"></span>
									</span>
									<input type="password" required="" placeholder="New Password" name="password" id="password" class="form-control" data-minlength="6">
								</div>
							</div>
						</div>
						<div class="form-group">
							<div class="col-lg-10 col-xs-10 col-sm-10 col-md-10 ">
								<div class="input-group">
									<span class="input-group-addon">
										<span class="glyphicon glyphicon-lock"></span>
									</span>
									<input type="password" required="" placeholder="Confirm Password" name="cpassword" id="cpassword" class="form-control" data-minlength="6">
								</div>
							</div>
						</div>
						<div class="form-group">
							<div class="col-lg-10 col-xs-10 col-sm-10 col-md-10 ">
								<div class="input-group col-lg-12 col-xs-12 col-sm-12 col-md-12 ">
									<input type="submit" value="Login" class="btn btn-primary btn-large">
									<a class="col-md-offset-8 formlink" href="#register" show="register" >Signup?</a>									
								</div>
								<a class="formlink" onclick="location.href='/user/resetPassword'">Forgot Password?</a>
							</div>
						</div>
					</fieldset>
				</form>
			</div>
		</div>
	</div>
</div>