<div class="login-box panel panel-default top-space">
    <div class="register-logo" style="margin-top:20px;margin-bottom:20px;">
		<a href="<?php echo $this->url->get(); ?>"><b>Phal</b>SAM</a>
	</div>
      <div class="login-box-body">
        <p class="login-box-msg">Sign in to start your session</p>
        <form method="post" action="/user/forgotpassword" class="form-horizontal">
			<input type="hidden" name="<?php echo $this->security->getTokenKey() ?>"
				value="<?php echo $this->security->getToken() ?>"/>
			<fieldset>
				<div class="form-group">
					<div class="col-lg-12 col-xs-12 col-sm-12 col-md-12 ">
						<div class="input-group">
							<span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
							<input type="text" required="" placeholder="Username/Email" name="username" id="username" class="form-control" data-minlength="6">
						</div>
					</div>
				</div>
				<div class="form-group">
					<div class="col-lg-10 col-xs-10 col-sm-10 col-md-10 ">
						<div class="input-group col-lg-12 col-xs-12 col-sm-12 col-md-12 ">
							<input type="submit" value="Reset Password" class="btn btn-primary btn-large">
						</div>
					</div>
				</div>
			</fieldset>
		</form>

        <div class="social-auth-links text-center">
          <p>- OR -</p>
          <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in using Facebook</a>
          <a href="#" class="btn btn-block btn-social btn-google-plus btn-flat"><i class="fa fa-google-plus"></i> Sign in using Google+</a>
        </div><!-- /.social-auth-links -->

        <a href="<?php echo $this->url->get('user/login'); ?>">Already Have an Account?</a><br>
        <a href="<?php echo $this->url->get('user/register'); ?>" class="text-center">Create an account with us</a>

      </div><!-- /.login-box-body -->
    </div><!-- /.login-box -->




