<div class="login-box panel panel-default top-space">
    <div class="register-logo" style="margin-top:20px;margin-bottom:20px;">
		<a href="<?php echo $this->url->get(); ?>"><b>Phal</b>SAM</a>
	</div>
      <div class="login-box-body">
        <p class="login-box-msg">Sign in to start your session</p>
        <form action="<?php echo $this->url->get('user/login'); ?>" method="post">
		<input type="hidden" name="<?php echo $this->security->getTokenKey() ?>"
					value="<?php echo $this->security->getToken() ?>"/>
          <div class="form-group has-feedback">
            <input type="text" class="form-control" name="username" placeholder="Email/Username"/>
            <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
          </div>
          <div class="form-group has-feedback">
            <input type="password" class="form-control" name="password" placeholder="Password"/>
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
          </div>
          <div class="row">
            <div class="col-xs-8">    
              <div class="checkbox icheck">
                <label>
                  <input type="checkbox"> Remember Me
                </label>
              </div>                        
            </div><!-- /.col -->
            <div class="col-xs-4">
              <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
            </div><!-- /.col -->
          </div>
        </form>

        <div class="social-auth-links text-center">
          <p>- OR -</p>
          <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in using Facebook</a>
          <a href="#" class="btn btn-block btn-social btn-google-plus btn-flat"><i class="fa fa-google-plus"></i> Sign in using Google+</a>
        </div><!-- /.social-auth-links -->

        <a href="<?php echo $this->url->get('user/forgotpassword'); ?>">I forgot my password</a><br>
        <a href="<?php echo $this->url->get('user/register'); ?>" class="text-center">Create an account with us</a>

      </div><!-- /.login-box-body -->
    </div><!-- /.login-box -->
<script>
  $(function () {
	$('input').iCheck({
	  checkboxClass: 'icheckbox_square-blue',
	  radioClass: 'iradio_square-blue',
	  increaseArea: '20%' // optional
	});
  });
</script>