<div class="panel panel-default register-box top-space">
	<div class="register-logo" style="margin-top:20px;margin-bottom:20px;">
		<a href="<?php echo $this->url->get(); ?>"><b>Phan</b>TOM</a>
	</div>
	<div class="register-box-body">
		<p class="login-box-msg">Create an account with us</p>
		<form method="post" action="/user/create" data-toggle="validator" id="register-form">
			<input type="hidden" name="<?php echo $this->security->getTokenKey() ?>"
					value="<?php echo $this->security->getToken() ?>"/>
			<div class="form-group has-feedback">
				<input type="text" name="fullname" class="form-control" placeholder="Full name" required/>
				<span class="glyphicon glyphicon-user form-control-feedback"></span>
				<div class="help-block with-errors"></div>
			</div>
			<div class="form-group has-feedback">
				<input type="text" data-minlength="6" class="form-control" id="username" name="username" placeholder="Username" required>
				<span class="glyphicon glyphicon-user form-control-feedback"></span>
				<div class="help-block with-errors"></div>
			</div>
			<div class="form-group has-feedback">
				<input type="email" class="form-control" name="email" id="inputEmail" placeholder="Email" data-error="Bruh, that email address is invalid" required="">
				<span class="glyphicon glyphicon-envelope form-control-feedback"></span>
				<div class="help-block with-errors"></div>
			</div>
			<div class="form-group has-feedback">
				<input type="password" class="form-control" id="rpassword" name="password" placeholder="Password" required/>
				<span class="glyphicon glyphicon-lock form-control-feedback"></span>
				<div class="help-block with-errors"></div>
			</div>
			<div class="form-group has-feedback">
				<input type="password" class="form-control" id="crPassword" name="cpassword" placeholder="Retype password" required/>
				<span class="glyphicon glyphicon-log-in form-control-feedback"></span>
				<div class="help-block with-errors"></div>
			</div>
			<div class="row">
				<div class="col-xs-8">    
					<div class="checkbox icheck">
						<label>
							<input type="checkbox"> I agree to the <a href="#">terms</a>
						</label>
					</div>                        
				</div><!-- /.col -->
				<div class="col-xs-4">
					<button type="submit" class="btn btn-primary btn-block btn-flat">Register</button>
				</div><!-- /.col -->
			</div>
		</form>        

		<div class="social-auth-links text-center">
			<p>- OR -</p>
			<a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign up using Facebook</a>
			<a href="#" class="btn btn-block btn-social btn-google-plus btn-flat"><i class="fa fa-google-plus"></i> Sign up using Google+</a>
		</div>
		<a href="<?php echo $this->url->get('user/login'); ?>" class="text-center">Already have an Account</a>
	</div><!-- /.form-box -->
</div><!-- /.register-box -->
<script>
  $(function () {
	$('input').iCheck({
	  checkboxClass: 'icheckbox_square-blue',
	  radioClass: 'iradio_square-blue',
	  increaseArea: '20%' // optional
	});
  });
</script>
<script type="text/javascript">
jQuery('form').on('submit',function(){
   if(jQuery('#rpassword').val()!=jQuery('#crPassword').val()){
       alert('Password not matches');
       return false;
   }
   return true;
});
</script>
