<?php echo $this->tag->getDoctype() ?>
<html>
    <head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta name="description" content="Mageking (description)" />
		<meta name="keywords" content="" />
		<meta name="author" content="Vinay Sikarwar">
		<meta name="robots" content="INDEX,FOLLOW" />
		<!--link rel="icon" href="" type="image/x-icon" />
		<link rel="shortcut icon" href="" type="image/x-icon" /-->
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<?php echo $this->tag->getTitle() ?>
		<?php echo $this->tag->stylesheetLink("css/bootstrap.min.css"); ?>
		<?php echo $this->tag->stylesheetLink("css/bootstrap-theme.min.css"); ?>
		<?php echo $this->tag->stylesheetLink("css/style.css"); ?>
		<?php echo $this->tag->stylesheetLink("css/jquery.dataTables.min.css"); ?>
		<?php echo $this->tag->stylesheetLink("dist/css/AdminLTE.min.css"); ?>
		
		<?php echo $this->tag->javascriptInclude("js/jquery-1.9.1.min.js"); ?>
		<?php echo $this->tag->javascriptInclude("js/noconflict.js"); ?>
		<?php echo $this->tag->javascriptInclude("js/angular.min.js"); ?>
		<?php echo $this->tag->javascriptInclude("js/bootstrap.min.js"); ?>
		<?php echo $this->tag->javascriptInclude("js/jquery.dataTables.min.js"); ?>
		<?php echo $this->tag->javascriptInclude("js/custom.js"); ?>
		<?php echo $this->tag->javascriptInclude("js/validator.js"); ?>
		
    </head>
    <body class="skin-default">
		<div class="wrapper">	
			<?php
				$currentUrl = $this->router->getRewriteUri();
				$isHideHeaderFooter = $this->helpers->isHideHeaderFooter($currentUrl);
				if(!$isHideHeaderFooter){
					$this->partial("page/html/header");
				}
			?>
			<div class="msg"><?php echo $this->flash->output(); ?></div>
			<div class="content"><?php echo $this->getContent() ?></div>
			<?php
				if(!$isHideHeaderFooter){
					?>
					<div class="footer"><?php $this->partial("page/html/footer"); ?></div>
					<?php
				}
			?>
		</div>
    </body>
</html>
